modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ben_10"
version="1.0.0"
displayName="Ben 10: Horizons"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Maketendo, OG20122012"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ben_10]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.ben_10]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ben_10]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration