name: Update File with Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Branch Name
      id: get_branch
      run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Update File with Branch Name
      run: |
        echo "$branch_name" > branch_name.txt
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add branch_name.txt
        git commit -m "Update branch.json with branch name"
        git push
